name: Continuous integration

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - name: Build zk-test-cluster
      working-directory: zk-test-cluster
      run: mvn clean package
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --all-features
